#%RAML 1.0 NamedExample

value:
    Status: Activated
    Products__c: 123
    AccountId: 0015g00000TjABtAA
    OrderNumber: 00000100
    Id: null
    TotalAmount: 85000.0
    type: Order
    Name: null
    EffectiveDate: 2021-10-06
  