#%RAML 1.0 NamedExample
value:
     wishlist__c : null 
     BillingCountry : null 
     BillingCity :  Mountain View  
     Phone :  (650) 867-3450  
     cart__c : null 
     ShippingCountry : null 
     ShippingState : null 
     ShippingCity : null 
     Id : null 
     type :  Account  
     BillingState :  CA  
     Name :  GenePoint 